spring.application.name=doctor-service

resilience4j.ratelimiter.instances.searchDoctorLimit.limit-for-period=5
resilience4j.ratelimiter.instances.searchDoctorLimit.limit-refresh-period=10s
resilience4j.ratelimiter.instances.searchDoctorLimit.timeout-duration=0

logging.level.io.github.resilience4j.ratelimiter=DEBUG
